/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.2 */

#ifndef PB_INDICADORES_PB_H_INCLUDED
#define PB_INDICADORES_PB_H_INCLUDED
#include "pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
typedef enum _Trama_Lapiz {
    Trama_Lapiz_TRI = 0,
    Trama_Lapiz_HEX = 1
} Trama_Lapiz;

typedef enum _Trama_Presion {
    Trama_Presion_HIPOTONICO = 0,
    Trama_Presion_HIPERTONICO = 1,
    Trama_Presion_NORMAL = 2
} Trama_Presion;

typedef enum _Trama_Agarre {
    Trama_Agarre_MODAL = 0,
    Trama_Agarre_DIGITAL = 1,
    Trama_Agarre_TRIDIGITAL = 2
} Trama_Agarre;

typedef enum _Trama_Direccionalidad {
    Trama_Direccionalidad_MALA = 0,
    Trama_Direccionalidad_BUENA = 1
} Trama_Direccionalidad;

typedef enum _Trama_Movimiento {
    Trama_Movimiento_PALMAR = 0,
    Trama_Movimiento_PRONSUP = 1
} Trama_Movimiento;

typedef enum _Trama_Animo {
    Trama_Animo_ESTRESADO = 0,
    Trama_Animo_CALMADO = 1
} Trama_Animo;

/* Struct definitions */
typedef struct _Trama {
    bool has_lapiz;
    Trama_Lapiz lapiz;
    bool has_bat_lapiz;
    uint32_t bat_lapiz;
    bool has_bat_pulsera;
    uint32_t bat_pulsera;
    bool has_presion;
    Trama_Presion presion;
    bool has_agarre;
    Trama_Agarre agarre;
    bool has_direccionalidad;
    Trama_Direccionalidad direccionalidad;
    bool has_animo;
    Trama_Animo animo;
    bool has_movimiento;
    Trama_Movimiento movimiento;
} Trama;


/* Helper constants for enums */
#define _Trama_Lapiz_MIN Trama_Lapiz_TRI
#define _Trama_Lapiz_MAX Trama_Lapiz_HEX
#define _Trama_Lapiz_ARRAYSIZE ((Trama_Lapiz)(Trama_Lapiz_HEX+1))

#define _Trama_Presion_MIN Trama_Presion_HIPOTONICO
#define _Trama_Presion_MAX Trama_Presion_NORMAL
#define _Trama_Presion_ARRAYSIZE ((Trama_Presion)(Trama_Presion_NORMAL+1))

#define _Trama_Agarre_MIN Trama_Agarre_MODAL
#define _Trama_Agarre_MAX Trama_Agarre_TRIDIGITAL
#define _Trama_Agarre_ARRAYSIZE ((Trama_Agarre)(Trama_Agarre_TRIDIGITAL+1))

#define _Trama_Direccionalidad_MIN Trama_Direccionalidad_MALA
#define _Trama_Direccionalidad_MAX Trama_Direccionalidad_BUENA
#define _Trama_Direccionalidad_ARRAYSIZE ((Trama_Direccionalidad)(Trama_Direccionalidad_BUENA+1))

#define _Trama_Movimiento_MIN Trama_Movimiento_PALMAR
#define _Trama_Movimiento_MAX Trama_Movimiento_PRONSUP
#define _Trama_Movimiento_ARRAYSIZE ((Trama_Movimiento)(Trama_Movimiento_PRONSUP+1))

#define _Trama_Animo_MIN Trama_Animo_ESTRESADO
#define _Trama_Animo_MAX Trama_Animo_CALMADO
#define _Trama_Animo_ARRAYSIZE ((Trama_Animo)(Trama_Animo_CALMADO+1))


/* Initializer values for message structs */
#define Trama_init_default                       {true, Trama_Lapiz_TRI, false, 0, false, 0, true, _Trama_Presion_MIN, true, _Trama_Agarre_MIN, true, _Trama_Direccionalidad_MIN, true, _Trama_Animo_MAX, true, _Trama_Movimiento_MIN}
#define Trama_init_zero                          {false, _Trama_Lapiz_MIN, false, 0, false, 0, false, _Trama_Presion_MIN, false, _Trama_Agarre_MIN, false, _Trama_Direccionalidad_MIN, false, _Trama_Movimiento_MIN, false, _Trama_Animo_MIN}

/* Field tags (for use in manual encoding/decoding) */
#define Trama_lapiz_tag                          1
#define Trama_bat_lapiz_tag                      2
#define Trama_bat_pulsera_tag                    3
#define Trama_presion_tag                        4
#define Trama_agarre_tag                         5
#define Trama_direccionalidad_tag                6
#define Trama_movimiento_tag                     8
#define Trama_animo_tag                          7

/* Struct field encoding specification for nanopb */
#define Trama_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UENUM,    lapiz,             1) \
X(a, STATIC,   OPTIONAL, UINT32,   bat_lapiz,         2) \
X(a, STATIC,   OPTIONAL, UINT32,   bat_pulsera,       3) \
X(a, STATIC,   OPTIONAL, UENUM,    presion,           4) \
X(a, STATIC,   OPTIONAL, UENUM,    agarre,            5) \
X(a, STATIC,   OPTIONAL, UENUM,    direccionalidad,   6) \
X(a, STATIC,   OPTIONAL, UENUM,    movimiento,        8) \
X(a, STATIC,   OPTIONAL, UENUM,    animo,             7)
#define Trama_CALLBACK NULL
#define Trama_DEFAULT NULL

extern const pb_msgdesc_t Trama_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define Trama_fields &Trama_msg

/* Maximum encoded size of messages (where known) */
#define Trama_size                               24

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
